### PR TITLE
disable export_all

### PR DESCRIPTION
**Pull request by getong**

### CODE REVIEW

**Comment by joewilliams** [comment]
What is the reasoning behind this change?

**Comment by getong** [comment]
bear/src/bear.erl:28: Warning: export_all flag enabled - all functions will be exported

**Comment by joewilliams** [comment]
I believe this was deliberate at some point. Can you please ensure that disabling this does not break any behavior in folsom?

**Comment by getong** [comment]
I will check it later, or we can export all functions.

**Comment by getong** [comment]
I run this command in the root of folsom:
```
grep -rn bear
```
and find that:
```
rebar.config.script:8:            {bear, ".*", {git, "https://github.com/folsom-project/bear.git", {tag, "0.8.5"}}},
rebar.config:1:%% can be simplified further once bear has been published to hex to simply the atom
rebar.config:2:%% 'bear'
rebar.config:4:    {bear, "0.8.5"}
src/folsom.app.src:13:                  bear
src/folsom_metrics.erl:192:    bear:get_statistics_subset(Values, WantedMetrics).
src/folsom_metrics.erl:197:    bear:get_statistics(Values1, Values2).
src/folsom_metrics_duration.erl:75:    Stats = bear:get_statistics_subset(Values, WantedMetrics),
README.md:17:       > application:ensure_all_started(bear). % start dependency first

```
so export get_statistics_subset/2 function just be fine.

**Pull request merged**
